### PR TITLE
Use clusterDeploymentName instead of label selector

### PR DESCRIPTION
**Pull request by mareklibra**

### CODE REVIEW

**Comment by rawagner** [comment]
we should probably remove the label from `infraenv-template.hbs` too

**Comment by rawagner** [comment]
+ set the `agentSelector/matchLabels` to empty object in `assisted-template.hbs`

**Comment by mareklibra** [comment]
> we should probably remove the label from `infraenv-template.hbs` too

ClusterDeployment is newly missing at all in that template.

**Comment by mareklibra** [comment]
>     * set the `agentSelector/matchLabels` to empty object in `assisted-template.hbs`

Thanks, done

**Pull request merged**
